## Center Value

- Fast way of assigning **something** to each territory
- A single point may or may not be representative of the entire territory
- Using the centroid here, but internal point may be better

```{r Centroid Lookup}
#| code-summary: "Centroid NLCD Lookup"
#| code-line-numbers: "|1-3|5-6|8-9|11-12|14-20"

# Transform CRS to match NLCD
new_york_county_tracts_nlcd_crs <- new_york_county_tracts %>%
  st_transform(crs(nlcd))

# Calculate the centroids of the tracts
centroids <- st_centroid(new_york_county_tracts_nlcd_crs)

# Extract values at centroids
centroid_values <- extract(nlcd, centroids, layer = 1)

# Read in land cover descriptions
nlcd_descriptions <- read_csv("references_public/nlcd_classes.csv")

# Bind data
centroid_values <- centroids %>%
  st_drop_geometry() %>% # Removes the geometry so we get a datatable
  bind_cols(centroid_values) %>%
  dplyr::select(GEOID, land_cover_code = value) %>%
  left_join(nlcd_descriptions) %>%
  arrange(GEOID, land_cover_code)
```

## Centroid Data Table

```{r Centroid Table}
#| code-summary: "Show code"
#| code-fold: true

datatable(centroid_values, rownames = FALSE)
```