
project:
  title: "20260503_geospatial_data_with_r"
  output-dir: docs
format:
  revealjs:
    theme: [simple, styles.scss]
    fontsize: 1.5em # 16px is standard, so this is 24 > 22 CAS minimum
    embed-resources: true
    slide-number: true
    echo: true
    code-fold: show
editor: 
  mode: source
  
title-slide-attributes: 
  data-background-image: images/tornado_yellow.png
  data-background-opacity: "0.2"