## National Land Cover Dataset (NLCD)

Giant Raster (pixel) image

```{r Download NLCD Raster}
#| echo: true
#| code-fold: true
#| code-summary: "Download NLCD Raster"
#| results: "hide"

url <- "https://www.mrlc.gov/downloads/sciweb1/shared/mrlc/data-bundles/Annual_NLCD_LndCov_2024_CU_C1V1.zip"
dest_in <- "./data_in/nlcd/Annual_NLCD_LndCov_2024_CU_C1V1.zip"
dest_mid <- "./data_mid/nlcd/Annual_NLCD_LndCov_2024_CU_C1V1.zip"

if(!file.exists(dest_in)) {
  dir.create(dirname(dest_in), recursive = TRUE, showWarnings = FALSE)
  curl_download(url, dest_in)
  
  dir.create(dirname(dest_mid), recursive = TRUE, showWarnings = FALSE)
  unzip(dest_in, exdir = dirname(dest_mid))
}

dest_mid

```

```{r Countrywide NLCD Raster}
#| echo: true
#| code-fold: true
#| code-summary: "Show code"

nlcd <- rast("data_mid/nlcd/Annual_NLCD_LndCov_2024_CU_C1V1.tif")
plot(nlcd)
```

::: {.notes }
National Land Cover Data set

Depicts the predominant thematic land cover class within the mapping year with respect to broad categories of artificial or natural surface cover

30m x 30m grid
105,000 x 160,000

:::

## NLCD in Manhattan

```{r NLCD Raster  trimmed to Manhattan}
#| echo: true
#| code-fold: true
#| code-summary: "Show code"

manhattan_county <- census_county %>%
  filter(GEOID == "36061") %>%
  st_transform(crs(nlcd))

# Mask = TRUE crops to the boards rather than a rectangle
nlcd_man <- crop(nlcd, manhattan_county, mask = TRUE)
```

```{r Plot NLCD for Manhattan}
#| echo: true
#| code-fold: true
#| code-summary: "Show code"

leaflet() %>%
addTiles() %>%
  addRasterImage(nlcd_man, opacity = 0.8) %>%
  addRasterLegend(nlcd_man, title = "NLCD Land Cover", opacity = 1)
```

