## Census Block Groups

```{r Download and Read New York Block Groups}
#| echo: true
#| code-fold: true
#| code-summary: "Download and Read New York Census Block Groups"
#| results: "hide"

url <- "https://www2.census.gov/geo/tiger/TIGER2025/BG/tl_2025_36_bg.zip"
dest_in <- "./data_in/census/TIGER2025/BG/tl_2025_36_bg.zip"
dest_mid <- "./data_mid/census/TIGER2025/BG/tl_2025_36_bg/tl_2025_36_bg.zip"

if(!file.exists(dest_in)) {
  dir.create(dirname(dest_in), recursive = TRUE, showWarnings = FALSE)
  curl_download(url, dest_in)
  
  dir.create(dirname(dest_mid), recursive = TRUE, showWarnings = FALSE)
  unzip(dest_in, exdir = dirname(dest_mid))
}

new_york_county_bg  <- read_sf("data_mid/census/TIGER2025/BG/tl_2025_36_bg/tl_2025_36_bg.shp") %>%
  filter(STATEFP == "36", COUNTYFP == "061")
```

```{r Plot Manhattan Block Groups}
#| echo: true
#| code-fold: true
#| code-summary: "Plot Manhattan Block Groups"

leaflet(new_york_county_bg) %>%
  addTiles() %>%
  addPolygons(weight = 0.5, opacity = 1.0)
```
  
::: {.notes}
Census tracts are broken into Census block groups

239,780 block groups in the 50 states + DC

:::