## MGRS

```{r Download and Read Military Grid Reference System}
#| echo: true
#| code-fold: true
#| code-summary: "Download and Read Military Grid Reference System"
#| results: "hide"

url <- "https://earth-info.nga.mil/php/download.php?file=MGRS_1km_18T_unprojected"
dest_in <- "./data_in/nga/mgrs/MGRS_1km_18T_unprojected.zip"
dest_mid <- "./data_mid/nga/mgrs/MGRS_1km_18T_unprojected/MGRS_1km_18T_unprojected.zip"

if(!file.exists(dest_in)) {
  dir.create(dirname(dest_in), recursive = TRUE, showWarnings = FALSE)
  curl_download(url, dest_in)
  
  dir.create(dirname(dest_mid), recursive = TRUE, showWarnings = FALSE)
  unzip(dest_in, exdir = dirname(dest_mid))
}

# Read MGRS 1 km grid Shapefile
mgrs  <- read_sf("./data_mid/nga/mgrs/MGRS_1km_18T_unprojected/MGRS_1km_18T_unprojected.shp") %>%
  st_crop(xmin = -74.05, xmax = -73.90, ymin = 40.65, ymax = 40.90)
```

```{r Read MGRS 18T Shapefile}
#| echo: true
#| code-fold: true
#| code-summary: "Show code"

# Filter county data set to Manhattan
manhattan_county <- census_county %>% filter(COUNTYFP == "061")

# Need to change the coordinate reference system of one of them to do the intersection
mgrs <- st_intersection(manhattan_county, st_transform(mgrs, st_crs(manhattan_county)))

# Plot
leaflet(mgrs) %>%
  addTiles() %>%
  addPolygons(weight = 0.5, opacity = 1.0)
```

::: {.notes}
- Construct your own grid use a pre-existing grid (for example, based on decimal degrees or MGRS)
- National Geospatial-Intelligence Agency (NGA)
- Typically don't line up with city, state, county, or ZIP boundaries
- Territories get narrower the higher up on the globe you are
:::
