## ZIP Codes (ZIP Code Tabulation Areas)

```{r Plot Manhattan-ish ZIP Code Tabulation Areas}
#| code-summary: "Leaflet Census ZIP Code Tabulation Areas Map - Manhattan County"
#| code-line-numbers: "|9-11"

# Download data using our helper function
download_data(
  url = "https://www2.census.gov/geo/tiger/TIGER2025/ZCTA520/tl_2025_us_zcta520.zip",
  relative_dir = "census/TIGER2025/ZCTA520")

# Read Shapefile
zcta  <- read_sf("./data_mid/census/TIGER2025/ZCTA520/tl_2025_us_zcta520.shp")

# Filter to New York, NY ZIP codes... sort of - Marble Hill Chopped off
zcta_manhattan <- zcta %>%
  filter(ZCTA5CE20 %in% c(as.character(seq(from = 10000, to = 10299))))

# Plot Leaflet Map
zcta_manhattan %>%
  leaflet() %>%
  addTiles() %>%
  addPolygons(weight = 0.5, opacity = 1.0)
```

::: {.notes}

Skipping straight to Manhattan since the New York State ZIP Codes added 40 MB to the size of the deck

Plus: People generally know their ZIP code, so that's nice

Minus:
Any ZIP boundaries are an interpretation of ZIP Codes.

If you buy the ZIP + 4 file from the USPS, you get a table of 43 million records. Not a map.
https://postalpro.usps.com/address-quality-solutions/zip-4-product

- Cross city, county, and state boundaries

These change rapidly. The methodology is valuable to read: https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html

- https://about.usps.com/postal-bulletin/2009/pb22262/html/updt_002.htm

Manhattan is a nice set of territories here. A couple of notes:
- UWS side zip codes go across Central Park
- Some buildings are their own ZIP code
- Being surrounded by water helps prevent ZIP codes from spreading to other areas
- Cobble Hill is missing. It's part of a bigger ZIP code and can't be carved out
:::

## ZIP Codes Pros/Cons

::: {.fragment}
- Pros:
  - People know their ZIP Code

:::

::: {.fragment}
- Cons:
  - Any visual geographic boundary representation is an artistic interpretation of the ZIP + 4 file from the USPS, which is a list of 43 million addresses
  - They can cross city, county, and state boundaries
  - Territory representations are neither:
    - ZIP Codes overlap
    - Some areas with currently no population don't get drawn inside a ZIP Code
  - There are 40,000+ changes per year. Visual representations like ZCTA don't pick up all the changes immediately
  - Some ZIP codes only represent a single building

:::