## Carrier 2

- Grid - Decimal degrees to two decimal places
- 2 Perils:
    - Hurricane 
    - Non-Hurricane
- Synthesized factors similar to the real factors, but not the actual factors

## Carrier 2 - Factor Table

```{r Read in Carrier 2 Territory Factor Table}
#| code-summary: "Read in Carrier 2 Factors & Construct Grid"
#| code-line-numbers: "|1-4|5-7|8|11-14"

# CSV extracted from PDF with synthetic factors
carrier_2_ny <- read_csv("./references_public/carrier_2_synthetic.csv",
                         col_names = c("GRID_ID", "HURR_FCTR", "NONHURR_FCTR"),
                         skip = 1)  %>%
  mutate( # This parses the coordinate out of GRID_ID
    y = round(  0.01 * as.numeric(substr(GRID_ID, 1, 5 )), 2),
    x = round(- 0.01 * as.numeric(substr(GRID_ID, 6, 10)), 2)) %>%
  select(GRID_ID, y, x, HURR_FCTR, NONHURR_FCTR)

# Create table
carrier_2_ny %>%
  datatable(rownames = FALSE) %>%
  formatRound(columns = c(2, 3), digits = 2) %>%
  formatRound(columns = c(4, 5), digits = 4)
```

## Carrier 2 - Synthetic Non-Hurricane Factors

```{r Carrier 2 NY Non-Hurricane Factors}
#| code-summary: "Create and plot Non-Hurricane Factor Raster"
#| code-line-numbers: "|1-2|4-10|12-16"

# Convert non-Hurricane Factors to Raster
nonhurr_ny <- rast(carrier_2_ny[, c("x", "y", "NONHURR_FCTR")], crs = crs('+proj=longlat +datum=WGS84'))

# Set up a color palette
pal <- colorBin(
  palette = c("#2c7bb6", "#abd9e9","#ffffbf","#fdae61","#d7191c"),
  domain = values(nonhurr_ny),
  bins = c(0.75, 1.00, 1.25, 1.5, 1.75),
  na.color = "transparent"
)

# Plot factors
leaflet() %>%
  addTiles() %>%
  addRasterImage(nonhurr_ny, colors = pal, opacity = 0.5) %>%
  addLegend(pal = pal, values = values(nonhurr_ny), title = "Non-Hurricane Factor")
```

## Carrier 2 - Synthetic Hurricane Factors

```{r Carrier 2 NY Hurricane Factors}
#| code-summary: "Create and plot Hurricane Factor Raster"
#| code-fold: true

# Convert Hurricane Factors to Raster
hurr_ny <- rast(carrier_2_ny[, c("x", "y", "HURR_FCTR")], crs = crs('+proj=longlat +datum=WGS84'))

# Set up a color palette
pal <- colorBin(
  palette = c("#2c7bb6", "#abd9e9","#ffffbf","#fdae61","#d7191c"),
  domain = values(hurr_ny),
  bins = c(0, 0.5, 1.5, 2.0, 2.5, 3.0),
  na.color = "transparent"
)

leaflet() %>%
  addTiles() %>%
  addRasterImage(hurr_ny, colors = pal, opacity = 0.5) %>%
  addLegend(pal = pal, values = values(hurr_ny), title = "Hurricane Factor")
```
